apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndjk-test-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ndjk-test
      version: blue
  template:
    metadata:
      labels:
        app: ndjk-test
        version: blue
    spec:
      containers:
        - name: ndjk-test
          image: my-docker-repository/ndjk-test:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ndjk-test
spec:
  selector:
    app: ndjk-test
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
